#!/usr/bin/env bash
# Web servers are the piece of software generating and
# Serving HTML pages, let’s install one!
#	Listens on port 80.
#	Returns a page containing "Holberton School" when queried
#	at the root with a curl GET request.

sudo -y apt-get update
sudo -y apt-get install nginx-full
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
