#!/usr/bin/env bash
# Web servers are the piece of software generating and
# Serving HTML pages, let’s install one!
#	Listens on port 80.
#	Returns a page containing "Holberton School" when queried
#	at the root with a curl GET request.

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'

touch /var/www/html/index
echo 'Hello World!' > /var/www/html/index.html

printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx start
