#!/usr/bin/env bash
# Web servers are the piece of software generating and
# Serving HTML pages, let’s install one!
#	Listens on port 80.
#	Returns a page containing "Holberton School" when queried
#	at the root with a curl GET request.

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

sudo echo "Hello World!" > /var/www/html/get-daniel.tech/index.nginx-debian.html

sudo service nginx restart
