#!/usr/bin/env bash
# Bash script with the minimum number of commands to automate your fix.

rm /etc/nginx/sites_enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
