#!/usr/bin/env bash
# Bash script with the minimum number of commands to automate your fix.
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
