#!/usr/bin/env bash
# Manages manage_my_process.

FILE="/var/run/my_process.pid"

function error()
{
    echo "Usage: manage_my_process {start|stop|restart}"
}

function start()
{
    (./manage_my_process) &
    echo $$ > $FILE
    echo "manage_py_process started"
}

function stop()
{
    pkill -f ./manage_my_process
    sudo rm $FILE
    echo "manage_my_process stopped"
}

function restart()
{
    pkill -f ./manage_my_process
    rm $FILE
    ./manage_my_process &
    echo $$ > $FILE
    echo "manage_my_process restarted"
}

if [ $# -ne 1 ];
then
    error
else
    case ${1} in
    	"Started")
    	    start;;
    	"restart")
    	    restart;;
    	"stop")
    	    stop;;
    	*)
    	    error;;
    esac
fi
