#!/usr/bin/env bash
# Loops from 1 to 20 and display:
#            4 and then bad luck from China for the 4th loop iteration.
#            9 and then bad luck from Japan for the 9th loop iteration.
#            17 and then bad luck from Italy for the 17th loop iteration.

index=1

while ((index <= 20))
do
	echo "$index"
	case $index in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
	esac
	((index++))
done
